# -*- coding: utf-8 -*-
"""Diffusion attempt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/taurusilver/diffusion-attempt.cf1540c2-d7d2-4ba1-9f13-64e6cf0e1847.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260715/auto/storage/goog4_request%26X-Goog-Date%3D20260715T081911Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D8c4154a31447e7dc63c5e293791f16385645095b2bf347d9b17908a177fd986af2ef58dfbbc82e8fcc50846be36daac73aef365ca5635cb58bfc55bc63d6fb7fe727cbd17f0b59d2117f7206f5e2cb813c33223fb47e037bb249dc9fc0fba765ba085d1b5f0ecc7c4941f8cda200fc3bad869419c904996a9c152ce43972fba75f071d428b4b6c70b9c17256aaabe582838b15ecef9f72220dd100c37f2c8351946c53861e8273bc88c13a32d1cc64e1719245f80a9fad42893525de2d0f2e4b238c63ec48a182d13b718f50fda0986503a94fac00924801f911258f92fb2e644accd970bc1bdc5e10bd7135a98d246522d327c12aab9e9a1d831c5105fcdc96
"""



import os

import os, math, time, json, random, inspect
import numpy as np
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import AdamW
from torch.optim.lr_scheduler import LambdaLR
from torch.utils.data import IterableDataset, DataLoader
import json
from datasets import load_dataset

print("torch:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("bf16 supported:", torch.cuda.is_bf16_supported())
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)


# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # Now create data directory, download, extract, and preprocess within DeepSC
# !mkdir -p data
# !wget http://www.statmt.org/europarl/v7/europarl.tgz
# !tar zxvf europarl.tgz
# !python preprocess_text.py

import os
import json
import pickle
import random
from dataclasses import dataclass
from tokenizers import Tokenizer as _RawTok
from transformers import PreTrainedTokenizerFast

# ---------------------------------------------------------------------------
# Dataset loading — uses the SAME canonical pkl splits as main.py
# ---------------------------------------------------------------------------
#
# The pkl files (txt/train_data.pkl etc.) store each sentence as a list of
# custom-vocab integer IDs (built by preprocess_text.py / the original DeepSC
# pipeline).  We decode those IDs back to plain text using txt/vocab.json, then
# re-tokenize with the existing diffusion WordLevel tokenizer so the diffusion
# model uses the correct vocabulary without any re-training or re-preprocessing.

DEEPSC_VOCAB_FILE  = 'txt/vocab.json'
DIFFUSION_VOCAB_FILE = 'txt/diffusion_vocab.json'
_SPECIAL_TOKENS = {'<PAD>', '<START>', '<END>', '<UNK>'}

# Load the custom DeepSC vocab for decoding pkl IDs → text
print('Loading DeepSC vocab...')
with open(DEEPSC_VOCAB_FILE) as f:
    _deepsc_vocab = json.load(f)
_token_to_idx  = _deepsc_vocab['token_to_idx']
_idx_to_token  = {int(v): k for k, v in _token_to_idx.items()}
_end_idx       = _token_to_idx['<END>']

def _ids_to_text(token_ids):
    """Convert a list of custom-vocab IDs to a plain text string."""
    words = []
    for idx in token_ids:
        idx = int(idx)
        if idx == _end_idx:
            break
        tok = _idx_to_token.get(idx, '')
        if tok and tok not in _SPECIAL_TOKENS:
            words.append(tok)
    return ' '.join(words)


def _load_split(split_name):
    pkl_path = f'txt/{split_name}_data.pkl'
    print(f'  Loading {pkl_path}...')
    with open(pkl_path, 'rb') as f:
        raw = pickle.load(f)
    texts = [_ids_to_text(row) for row in raw]
    texts = [t for t in texts if t.strip()]
    print(f'  {len(texts)} non-empty sentences from {split_name}')
    return texts


print('Loading canonical train/val/test splits from pkl files...')
train_texts = _load_split('train')
val_texts   = _load_split('val')
test_texts  = _load_split('test')
print(f'Total: {len(train_texts)+len(val_texts)+len(test_texts)} sentences '
      f'({len(train_texts)} train / {len(val_texts)} val / {len(test_texts)} test)')
print('Sample train sentence:', train_texts[0])

# Re-tokenize with the existing diffusion vocabulary (no re-training needed)
print('Re-tokenizing with diffusion tokenizer...')
_raw_tok = _RawTok.from_file(DIFFUSION_VOCAB_FILE)
hf_tokenizer = PreTrainedTokenizerFast(tokenizer_file=DIFFUSION_VOCAB_FILE)
PAD_ID = hf_tokenizer.convert_tokens_to_ids('<PAD>') or 0

def _tokenize(texts):
    return [enc.ids for enc in _raw_tok.encode_batch(texts)]

train_data = _tokenize(train_texts)
val_data   = _tokenize(val_texts)
test_data  = _tokenize(test_texts)
print(f'Tokenized.  Vocab size: {len(hf_tokenizer)}')
print(f'Example encoding: {train_data[0][:12]}')

# =======================
# 0) Choose a run profile
# =======================

RUN_MODE = "budget_100"   # "quick" or "budget_100"

if RUN_MODE == "quick":
    SEQ_LEN        = 32
    D_MODEL        = 384
    N_LAYERS       = 6
    N_HEADS        = 6
    D_FF           = 4 * D_MODEL
    DIFFUSION_STEPS = 64
    BATCH_SIZE     = 32
    GRAD_ACCUM     = 1
    LR             = 3e-4
    WEIGHT_DECAY   = 0.1
    WARMUP_STEPS   = 200

elif RUN_MODE == "budget_100":
    SEQ_LEN        = 32
    D_MODEL        = 512
    N_LAYERS       = 10
    N_HEADS        = 8
    D_FF           = 4 * D_MODEL
    DIFFUSION_STEPS = 128
    BATCH_SIZE     = 32
    GRAD_ACCUM     = 2
    LR             = 2e-4
    WEIGHT_DECAY   = 0.1
    WARMUP_STEPS   = 1_000

else:
    raise ValueError("RUN_MODE must be 'quick' or 'budget_100'")

print("RUN_MODE:", RUN_MODE)

# =======================
# Model Configuration
# =======================

@dataclass
class ChannelDiffusionConfig:
    vocab_size: int
    seq_len: int
    d_model: int
    n_enc_layers: int
    n_dec_layers: int
    n_heads: int
    d_ff: int
    dropout: float = 0.1
    diffusion_steps: int = 5
    sigma_min: float = 0.002
    sigma_max: float = 1.0        # Fix #1: match LayerNorm output scale (std ≈ 1.0)
    channel_type: str = "Rayleigh"
    snr_gamma: float = 5.0        # Fix #4: consolidated Min-SNR-γ clipping value
    n_snr_bins: int = 19          # discrete SNR bins covering 0..18 dB evaluation range
def SNR_to_noise(snr):
    snr = 10 ** (snr / 10)
    noise_std = 1 / np.sqrt(2 * snr)

    return noise_std
class Channels():
    def AWGN(self, Tx_sig, n_var):
        Rx_sig = Tx_sig + torch.randn_like(Tx_sig) * n_var
        return Rx_sig

    def Rayleigh(self, Tx_sig, n_var):
        shape = Tx_sig.shape                       # [B, L, D]
        B, device = shape[0], Tx_sig.device

        # Per-example fading coefficients (was: one scalar H shared by whole batch)
        H_real = torch.normal(0, math.sqrt(1 / 2), size=(B,), device=device)
        H_imag = torch.normal(0, math.sqrt(1 / 2), size=(B,), device=device)
        H = torch.stack([
            torch.stack([H_real, -H_imag], dim=-1),
            torch.stack([H_imag,  H_real], dim=-1),
        ], dim=-2)                                  # [B, 2, 2]

        Tx_pairs = Tx_sig.reshape(B, -1, 2)          # [B, L*D/2, 2]
        Tx_faded = torch.bmm(Tx_pairs, H)            # [B, L*D/2, 2]
        Rx_faded = self.AWGN(Tx_faded, n_var)        # n_var: [B,1,1] broadcasts fine
        Rx_sig   = torch.bmm(Rx_faded, torch.inverse(H)).reshape(shape)
        return Rx_sig

    def Rician(self, Tx_sig, n_var, K=1):
        shape = Tx_sig.shape
        B, device = shape[0], Tx_sig.device
        mean = math.sqrt(K / (K + 1))
        std  = math.sqrt(1 / (K + 1))

        H_real = torch.normal(mean, std, size=(B,), device=device)
        H_imag = torch.normal(mean, std, size=(B,), device=device)
        H = torch.stack([
            torch.stack([H_real, -H_imag], dim=-1),
            torch.stack([H_imag,  H_real], dim=-1),
        ], dim=-2)                                  # [B, 2, 2]

        Tx_pairs = Tx_sig.reshape(B, -1, 2)
        Tx_faded = torch.bmm(Tx_pairs, H)
        Rx_faded = self.AWGN(Tx_faded, n_var)
        Rx_sig   = torch.bmm(Rx_faded, torch.inverse(H)).reshape(shape)
        return Rx_sig

    def forward(self, Tx_sig, n_var, channel_type="AWGN", K=1):
        if channel_type == "AWGN":
            return self.AWGN(Tx_sig, n_var)
        elif channel_type == "Rayleigh":
            return self.Rayleigh(Tx_sig, n_var)
        elif channel_type == "Rician":
            return self.Rician(Tx_sig, n_var, K=K)
        elif channel_type is None or channel_type == "None":
            return Tx_sig
        else:
            raise ValueError(f"Unknown channel_type: {channel_type}")



from torch.utils.data import IterableDataset, DataLoader

class TokenSentenceDataset(IterableDataset):
    def __init__(self, tokenized_ds, seq_len, shuffle=False, seed=0, pad_id=0):
        """
        Args:
            tokenized_ds: A list of lists containing token IDs (e.g., train_data)
            seq_len: The desired sequence length; each sentence is truncated/padded to this length
            shuffle: Whether to shuffle the sentences
            seed: Random seed for shuffling
            pad_id: Token ID used for right-padding (should match <PAD> index)
        """
        self.tokenized_ds = tokenized_ds
        self.seq_len = seq_len
        self.shuffle = shuffle
        self.seed = seed
        self.pad_id = pad_id

    def __iter__(self):
        indices = list(range(len(self.tokenized_ds)))
        if self.shuffle:
            epoch_seed = self.seed + random.randint(0, 1000000)
            rng = random.Random(epoch_seed)
            rng.shuffle(indices)

        for idx in indices:
            ids = self.tokenized_ds[idx][:self.seq_len]          # truncate
            pad_len = self.seq_len - len(ids)
            ids = ids + [self.pad_id] * pad_len                  # right-pad
            yield torch.tensor(ids, dtype=torch.long)

train_blocks = TokenSentenceDataset(train_data, SEQ_LEN, shuffle=True, seed=10, pad_id=PAD_ID)
val_blocks   = TokenSentenceDataset(val_data,   SEQ_LEN, shuffle=False, pad_id=PAD_ID)
test_blocks  = TokenSentenceDataset(test_data,  SEQ_LEN, shuffle=False, pad_id=PAD_ID)

def collate_blocks(batch):
    input_ids = torch.stack(batch, dim=0)  # [B, L]
    attention_mask = (input_ids != PAD_ID)
    return {"input_ids": input_ids, "attention_mask": attention_mask}

train_loader = DataLoader(train_blocks, batch_size=BATCH_SIZE, collate_fn=collate_blocks)
val_loader   = DataLoader(val_blocks,   batch_size=BATCH_SIZE, collate_fn=collate_blocks)
test_loader  = DataLoader(test_blocks,  batch_size=BATCH_SIZE, collate_fn=collate_blocks)

# Verify a batch
b = next(iter(train_loader))
print({k: v.shape for k, v in b.items()})
print("Decoded snippet:\n", hf_tokenizer.decode(b["input_ids"][0][:120].tolist()))
print(f"Dataset sizes: {len(train_data)} train / {len(val_data)} val / {len(test_data)} test")

def make_sigma_schedule(T, sigma_min=0.01, sigma_max=1.0, device="cuda"):
    # sigma[0] = sigma_min ... sigma[T] = sigma_max, geometric interpolation
    steps = torch.arange(T + 1, device=device).float() / T
    sigmas = sigma_min * (sigma_max / sigma_min) ** steps
    return sigmas  # shape [T+1], index with integer t in [0, T]

class ChannelDiffusionLM(nn.Module):
    def __init__(self, cfg: ChannelDiffusionConfig):
        super().__init__()
        self.cfg = cfg
        self.channels = Channels()

        self.tok_emb = nn.Embedding(cfg.vocab_size, cfg.d_model)
        self.pos_emb = nn.Embedding(cfg.seq_len, cfg.d_model)
        self.time_emb = nn.Embedding(cfg.diffusion_steps + 1, cfg.d_model)

        # --- ELF Mode Embedding ---
        # Index 0 = Denoising Mode, Index 1 = Decoding/Rounding Mode
        self.mode_emb = nn.Embedding(2, cfg.d_model)

        # --- SNR Conditioning Embedding ---
        # Maps discrete SNR bin (0..n_snr_bins-1) → d_model context vector so the
        # denoiser can adapt its denoising strength to the physical channel quality.
        self.snr_emb = nn.Embedding(cfg.n_snr_bins, cfg.d_model)

        self.drop = nn.Dropout(cfg.dropout)

        # ELF simplifies the model into a unified backbone rather than a separate enc/dec split
        # but we can preserve your architecture and treat the 'denoiser' as the unified flow engine.
        self.encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=cfg.d_model, nhead=cfg.n_heads, dim_feedforward=cfg.d_ff,
                dropout=cfg.dropout, batch_first=True, activation="gelu", norm_first=True,
            ), num_layers=cfg.n_enc_layers
        )
        self.z_ln = nn.LayerNorm(cfg.d_model)

        self.denoiser = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=cfg.d_model, nhead=cfg.n_heads, dim_feedforward=cfg.d_ff,
                dropout=cfg.dropout, batch_first=True, activation="gelu", norm_first=True,
            ), num_layers=cfg.n_dec_layers
        )
        self.ln_f = nn.LayerNorm(cfg.d_model)

        self.lm_head = nn.Linear(cfg.d_model, cfg.vocab_size, bias=False)
        self.lm_head.weight = self.tok_emb.weight

        sigmas = make_sigma_schedule(cfg.diffusion_steps, cfg.sigma_min, cfg.sigma_max)
        self.register_buffer("sigmas", sigmas)

    def encode(self, input_ids, attention_mask=None):
        B, L = input_ids.shape
        pos = torch.arange(L, device=input_ids.device).unsqueeze(0)
        x = self.drop(self.tok_emb(input_ids) + self.pos_emb(pos))
        src_key_padding_mask = None if attention_mask is None else ~attention_mask
        x = self.encoder(x, src_key_padding_mask=src_key_padding_mask)
        z0 = self.z_ln(x)
        return z0

    def denoise_step(self, z_t, t, mode_idx=0, attention_mask=None, snr_bin=None):
        """
        ELF Denoising step with optional SNR conditioning.
        Fix #3: Re-inject fresh positional embeddings so the denoiser can recover
        sequence order even when high noise has washed out the original pos signal.

        Args:
            snr_bin: optional LongTensor [B] — discrete SNR bin (0..n_snr_bins-1).
                     Injects channel-quality context so the denoiser adapts its
                     denoising strength to the actual physical channel conditions.
        """
        B, L, D = z_t.shape
        t_emb = self.time_emb(t).unsqueeze(1)  # [B, 1, D]

        # Mode Embedding (0 = denoise, 1 = decode/round)
        modes = torch.full((B,), mode_idx, dtype=torch.long, device=z_t.device)
        m_emb = self.mode_emb(modes).unsqueeze(1)  # [B, 1, D]

        # Fix #3: Re-inject positional embeddings to preserve sequence order under noise.
        pos   = torch.arange(L, device=z_t.device).unsqueeze(0)  # [1, L]
        p_emb = self.pos_emb(pos)                                 # [1, L, D]

        # Combine: noisy latent + timestep + mode + position
        x = z_t + t_emb + m_emb + p_emb

        # SNR conditioning: inject channel-quality context into every token position
        if snr_bin is not None:
            s_emb = self.snr_emb(snr_bin).unsqueeze(1)  # [B, 1, D]
            x = x + s_emb

        src_key_padding_mask = None if attention_mask is None else ~attention_mask
        x = self.denoiser(x, src_key_padding_mask=src_key_padding_mask)
        z0_hat = self.ln_f(x)
        return z0_hat

        def forward(self, input_ids, t, mode_idx=0, attention_mask=None, channel_type=None,
            snr_bin=None):
            ctype = channel_type if channel_type is not None else self.cfg.channel_type
            z0 = self.encode(input_ids, attention_mask)

            if mode_idx == 1:
                # Decode/rounding mode: always use clean z0 (t=0, no noise).
                t_zero = torch.zeros_like(t)
                z0_hat = self.denoise_step(z0, t_zero, mode_idx=1, attention_mask=attention_mask,
                                        snr_bin=snr_bin)
            else:
                # Denoising mode: corrupt z0 through the SELECTED physical channel, then denoise.
                sigma_t = self.sigmas[t].view(-1, 1, 1)  # [B, 1, 1]
                z_t     = self.channels.forward(z0, sigma_t, channel_type=ctype)
                z0_hat  = self.denoise_step(z_t, t, mode_idx=0, attention_mask=attention_mask,
                                            snr_bin=snr_bin)

            # Fix #2: Scale logits by 1/√d_model to prevent logit explosion.
            logits = self.lm_head(z0_hat) / math.sqrt(self.cfg.d_model)
            return logits, z0, z0_hat

def channel_diffusion_loss(model, batch, lambda_ce=1.0, lambda_ce_denoise=0.1,
                            channel_type=None):
    device = next(model.parameters()).device
    input_ids = batch["input_ids"].to(device)
    attention_mask = batch["attention_mask"].to(device)
    B = input_ids.size(0)
    mask = attention_mask.unsqueeze(-1).float()

    z0 = model.encode(input_ids, attention_mask)

    snr_db_vals = torch.empty(B, device=device).uniform_(0, 18)
    snr_linear  = 10 ** (snr_db_vals / 10)
    noise_stds  = (1.0 / (2.0 * snr_linear).sqrt()).view(-1, 1, 1)
    snr_bin     = snr_db_vals.long().clamp(0, model.cfg.n_snr_bins - 1)

    t = torch.randint(1, model.cfg.diffusion_steps + 1, (B,), device=device)

    # --- Corrupt z0 → z_t using the SELECTED physical channel ---
    ctype = channel_type if channel_type is not None else model.cfg.channel_type
    z_t = model.channels.forward(z0, noise_stds, channel_type=ctype)

    z0_hat = model.denoise_step(z_t, t, mode_idx=0, attention_mask=attention_mask,
                                snr_bin=snr_bin)

    # --- Min-SNR-γ loss weighting using physical noise levels ---
    # High-noise batches (large noise_stds) dominate MSE gradients without weighting;
    # this clip prevents them from drowning out the low-noise learning signal.
    snr_t    = 1.0 / noise_stds.clamp_min(1e-6) ** 2           # [B, 1, 1]
    weight_t = snr_t.clamp(max=model.cfg.snr_gamma) / snr_t    # [B, 1, 1] ∈ (0, 1]

    per_token_mse = ((z0_hat - z0) ** 2).mean(dim=-1, keepdim=True)  # [B, L, 1]
    denom = (weight_t * mask).sum().clamp_min(1)
    mse = (per_token_mse * weight_t * mask).sum() / denom

    # --- CE auxiliary loss on the denoising path ---
    targets = input_ids.clone()
    targets[~attention_mask] = -100
    logits_denoise = model.lm_head(z0_hat) / math.sqrt(model.cfg.d_model)  # [B, L, V]
    ce_denoise = F.cross_entropy(
        logits_denoise.view(-1, logits_denoise.size(-1)),
        targets.view(-1),
        ignore_index=-100,
    )

    # --- CE Decode Path (mode=1): learn clean latent → token mapping ---
    # Use max-SNR bin (18 dB) for the decode path since z0 is clean (no channel noise).
    mode_mask     = (torch.rand(B, device=device) < 0.2).long()
    snr_bin_clean = torch.full((B,), model.cfg.n_snr_bins - 1,
                               dtype=torch.long, device=device)
    z_round = model.denoise_step(z0, torch.zeros(B, dtype=torch.long, device=device),
                                  mode_idx=1, attention_mask=attention_mask,
                                  snr_bin=snr_bin_clean)
    logits_decode = model.lm_head(z_round) / math.sqrt(model.cfg.d_model)

    ce_decode = F.cross_entropy(logits_decode.view(-1, logits_decode.size(-1)),
                                targets.view(-1), ignore_index=-100)

    decode_frac = mode_mask.float().mean().clamp_min(0.01)
    loss = mse + lambda_ce_denoise * ce_denoise + lambda_ce * decode_frac * ce_decode
    return loss, {"mse": mse.item(), "ce_denoise": ce_denoise.item(),
                  "ce_decode": ce_decode.item(), "t_mean": t.float().mean().item()}

def sigma_to_t(model, sigma: float) -> int:
    """
    Invert the geometric noise schedule sigma(t) = sigma_min * (sigma_max/sigma_min)^(t/T)
    to find the discrete timestep t that corresponds to a given noise standard deviation.

    Returns an integer in [1, T] so it is always a valid index into model.sigmas.
    """
    T = model.cfg.diffusion_steps
    sigma_clamped = max(model.cfg.sigma_min, min(model.cfg.sigma_max, sigma))
    frac = math.log(sigma_clamped / model.cfg.sigma_min) / math.log(model.cfg.sigma_max / model.cfg.sigma_min)
    t = round(frac * T)
    return max(1, min(T, t))


def noise_to_snr_bin(noise_std: float, n_snr_bins: int = 19) -> int:
    """Convert a noise standard deviation to the nearest discrete SNR bin.

    Inverse of SNR_to_noise: computes SNR_dB from noise_std, then clips to
    the integer bin index [0, n_snr_bins-1] covering 0..18 dB.
    """
    snr_linear = 1.0 / max(2.0 * noise_std ** 2, 1e-8)
    snr_db     = 10.0 * math.log10(snr_linear)
    return max(0, min(n_snr_bins - 1, round(snr_db)))


# Maximum DDIM denoising iterations. DDIM can skip timesteps, so only a small
# number of steps are needed to traverse t_start → 1. Running too many steps
# (e.g. 100+) causes cumulative drift that collapses token predictions.
MAX_DDIM_STEPS = 10


@torch.no_grad()
def reverse_sample(model, z_T, attention_mask=None, n_steps=None, t_start=None,
                   snr_bin=None, temperature=0.8):
    """
    DDIM-style deterministic reverse sampling.

    t_start:     discrete timestep matching the actual channel noise (from sigma_to_t).
    n_steps:     DDIM steps, capped at MAX_DDIM_STEPS=10 to prevent drift/collapse.
    snr_bin:     LongTensor [B] — discrete SNR bin for denoiser conditioning.
    temperature: final decode temperature; values < 1 sharpen the token distribution
                 and reduce mode-collapse (argmax = temperature → 0).
    """
    T = model.cfg.diffusion_steps
    if t_start is None:
        t_start = T
    t_start = max(1, min(T, int(t_start)))
    # Cap at MAX_DDIM_STEPS: DDIM can jump from t_start to t=1 in few steps by
    # skipping intermediate timesteps — no need to run every one of the 128 steps.
    n_steps = min(n_steps or t_start, MAX_DDIM_STEPS)
    B = z_T.size(0)
    z_t = z_T
    ts = torch.linspace(t_start, 1, n_steps, device=z_T.device).long()

    SIGMA_EARLY_EXIT = model.sigmas[2].item() if model.cfg.diffusion_steps >= 2 else 0.0

    for i in range(n_steps):
        t_cur     = ts[i].expand(B)
        sigma_cur = model.sigmas[t_cur].view(-1, 1, 1)

        z0_hat = model.denoise_step(z_t, t_cur, mode_idx=0, attention_mask=attention_mask,
                                    snr_bin=snr_bin)

        is_last  = (i == n_steps - 1)
        is_clean = (sigma_cur.mean().item() <= SIGMA_EARLY_EXIT)
        if is_last or is_clean:
            z_t = z0_hat
            break

        sigma_next     = model.sigmas[ts[i + 1].expand(B)].view(-1, 1, 1)
        raw_direction  = (z_t - z0_hat) / sigma_cur.clamp_min(1e-4)
        direction_norm = raw_direction.norm(dim=-1, keepdim=True).clamp_min(1e-6)
        max_norm       = 10.0
        direction      = raw_direction * (direction_norm.clamp_max(max_norm) / direction_norm)
        z_t            = z0_hat + sigma_next * direction

    # Last-Mile Decode (mode=1): project clean latent → tokens with SNR conditioning.
    snr_bin_final = snr_bin if snr_bin is not None else \
                    torch.full((B,), model.cfg.n_snr_bins - 1, dtype=torch.long, device=z_T.device)
    z_final = model.denoise_step(z_t, torch.zeros(B, dtype=torch.long, device=z_T.device),
                                  mode_idx=1, attention_mask=attention_mask,
                                  snr_bin=snr_bin_final)
    logits = model.lm_head(z_final) / math.sqrt(model.cfg.d_model)

    # Temperature-scaled sampling reduces token-collapse vs. greedy argmax.
    if temperature > 0 and temperature != 1.0:
        probs = F.softmax(logits / temperature, dim=-1)
        B_, L_, V_ = probs.shape
        token_ids = torch.multinomial(probs.view(-1, V_), num_samples=1).view(B_, L_)
    else:
        token_ids = logits.argmax(-1)
    return token_ids, logits

cfg = ChannelDiffusionConfig(
    vocab_size=len(hf_tokenizer),
    seq_len=32,
    d_model=D_MODEL,
    # n_enc_layers=N_LAYERS // 2,
    # n_dec_layers=N_LAYERS // 2,
    n_enc_layers=N_LAYERS // 2,
    n_dec_layers=N_LAYERS // 2,
    n_heads=N_HEADS,
    d_ff=D_FF,
    dropout=0.1,
    diffusion_steps=DIFFUSION_STEPS,
    sigma_min=0.002,
    sigma_max=1.0,        # Fix #1: matches LayerNorm output scale (std ≈ 1.0)
    channel_type="Rayleigh",
    snr_gamma=5.0,        # Fix #4: consolidated γ used by both train and eval
    n_snr_bins=19,        # SNR conditioning bins: 0..18 dB (matches evaluation range)
)
model = ChannelDiffusionLM(cfg).to(device)
def print_model_parameters(model: torch.nn.Module):
    """
    Prints a detailed breakdown of the model's parameters,
    taking into account weight sharing (like the tied LM head).
    """
    total_params = 0
    trainable_params = 0
    unique_params_set = set()

    print(f"{'Module Name':<45} | {'Shape':<20} | {'Parameters':<15} | {'Requires Grad'}")
    print("-" * 95)

    for name, param in model.named_parameters():
        param_id = id(param)
        is_shared = param_id in unique_params_set
        unique_params_set.add(param_id)

        num_params = param.numel()
        grad_status = str(param.requires_grad)
        shape_str = str(list(param.shape))

        # We flag shared weights (like lm_head.weight tied to tok_emb.weight)
        display_name = f"{name} (Shared)" if is_shared else name
        print(f"{display_name:<45} | {shape_str:<20} | {num_params:<15,} | {grad_status}")

        if not is_shared:
            total_params += num_params
            if param.requires_grad:
                trainable_params += num_params

    print("-" * 95)
    print(f"Total Unique Parameters:     {total_params:,}")
    print(f"Total Trainable Parameters:  {trainable_params:,}")

print_model_parameters(model)
# training step
# loss, stats = channel_diffusion_loss(model, batch)
# loss.backward()

# ----------------------------------------------------------------------
# Config for the training run itself
# ----------------------------------------------------------------------
TOTAL_STEPS = 200000        # <-- set this directly instead of NUM_EPOCHS * len(train_loader)
LR = 3e-4
WEIGHT_DECAY = 0.01
WARMUP_STEPS = 500
GRAD_CLIP = 1.0
LOG_EVERY = 50
EVAL_EVERY = 500
SAMPLE_EVERY = 1000
LAMBDA_CE = 1.0
CKPT_PATH = "channel_diffusion_ori_ckpt_Rayleigh.pt"

device = next(model.parameters()).device

def make_lr_lambda(warmup_steps, total_steps):
    def lr_lambda(step):
        if step < warmup_steps:
            return step / max(1, warmup_steps)
        progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
        return 0.5 * (1 + math.cos(math.pi * min(progress, 1.0)))
    return lr_lambda

optimizer = AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = LambdaLR(optimizer, lr_lambda=make_lr_lambda(WARMUP_STEPS, TOTAL_STEPS))

@torch.no_grad()
def evaluate(model, val_loader, n_batches=20):
    """Validate by calling channel_diffusion_loss directly to exactly mirror training."""
    model.eval()
    total_loss, total_mse, total_ce, n = 0.0, 0.0, 0.0, 0
    for i, batch in enumerate(val_loader):
        if i >= n_batches:
            break
        batch = {k: v.to(device) for k, v in batch.items()}
        loss, stats = channel_diffusion_loss(model, batch, lambda_ce=LAMBDA_CE)
        total_loss += loss.item()
        total_mse  += stats['mse']
        total_ce   += stats['ce_decode']
        n += 1
    model.train()
    return {"val_loss": total_loss / n, "val_mse": total_mse / n, "val_ce": total_ce / n}

@torch.no_grad()
def sanity_check_sample(model, batch, tokenizer, n_show=2, n_var=None):
    """
    Evaluate the model as a semantic channel codec:
      source → Encoder → z0 → AWGN(z0, sigma_T) → Reverse Diffusion → pred tokens

    This is the CORRECT evaluation protocol. The model was trained to denoise
    corrupted encodings, NOT to generate from pure zero-mean Gaussian noise.
    Starting from pure N(0, sigma_T^2) noise (previous approach) is out-of-
    distribution and causes the DDIM to collapse to one repeated token.
    """
    model.eval()
    batch = {k: v.to(device) for k, v in batch.items()}
    input_ids = batch["input_ids"][:n_show]
    attention_mask = batch["attention_mask"][:n_show]

    z0 = model.encode(input_ids, attention_mask)   # ground-truth semantic latent
    T  = model.cfg.diffusion_steps
    sigma_T = model.sigmas[T].item()

    # Use the provided noise std or default to sigma_max (worst-case channel)
    noise_std = n_var if n_var is not None else sigma_T

    # Invert the noise schedule to find the correct starting timestep.
    # Low noise_std → small t_start → short reverse chain (less drift / collapse risk).
    # High noise_std → t_start ≈ T → full reverse chain as before.
    t_start = sigma_to_t(model, noise_std)

    # Compute SNR bin from noise_std for denoiser conditioning
    snr_bin_val   = noise_to_snr_bin(noise_std, model.cfg.n_snr_bins)
    B_show        = z0.size(0)
    snr_bin       = torch.full((B_show,), snr_bin_val, dtype=torch.long, device=z0.device)

    # Simulate the physical channel: z_T = z0 + AWGN(0, noise_std)
    #change this to use Channels
    z_T = model.channels.Rayleigh(z0, noise_std)
    # Run DDIM reverse diffusion (capped at MAX_DDIM_STEPS to prevent drift)
    pred_ids, _ = reverse_sample(model, z_T, attention_mask=attention_mask,
                                 t_start=t_start, snr_bin=snr_bin)

    # --- Baseline: direct decode from clean z0 (upper bound, no channel noise) ---
    t_zero        = torch.zeros(B_show, dtype=torch.long, device=z0.device)
    snr_bin_clean = torch.full((B_show,), model.cfg.n_snr_bins - 1,
                               dtype=torch.long, device=z0.device)
    z_clean = model.denoise_step(z0, t_zero, mode_idx=1, attention_mask=attention_mask,
                                 snr_bin=snr_bin_clean)
    direct_ids = (model.lm_head(z_clean) / math.sqrt(model.cfg.d_model)).argmax(-1)

    print(f"  [channel σ={noise_std:.4f}, t_start={t_start}/{T}, SNR≈{(z0.std()/noise_std).item():.1f}dB]")
    for i in range(n_show):
        mask_i = attention_mask[i]
        gt     = tokenizer.decode(input_ids[i][mask_i].tolist(),   skip_special_tokens=True)
        direct = tokenizer.decode(direct_ids[i][mask_i].tolist(),  skip_special_tokens=True)
        pred   = tokenizer.decode(pred_ids[i][mask_i].tolist(),    skip_special_tokens=True)
        print(f"  GT     : {gt}")
        print(f"  Direct : {direct}")   # should be near-perfect if CE head is trained
        print(f"  Diffuse: {pred}")     # DDIM recovery through the noisy channel
        print()
    model.train()

def train(model, train_loader, val_loader, tokenizer, total_steps):
    step = 0
    best_val_loss = float("inf")
    model.train()

    train_iter = iter(train_loader)
    start_time = time.time()

    while step < total_steps:
        try:
            batch = next(train_iter)
        except StopIteration:
            # IterableDataset exhausted (e.g. one pass through a finite stream) -> restart it
            train_iter = iter(train_loader)
            batch = next(train_iter)

        batch = {k: v.to(device) for k, v in batch.items()}

        loss, stats = channel_diffusion_loss(model, batch, lambda_ce=LAMBDA_CE, channel_type="Rayleigh")


        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
        optimizer.step()
        scheduler.step()

        if step % LOG_EVERY == 0:
            lr_now = scheduler.get_last_lr()[0]
            elapsed = time.time() - start_time
            print(f"step {step}/{total_steps} | loss {loss.item():.4f} "
                  f"(mse {stats['mse']:.4f}, ce_d {stats['ce_denoise']:.4f}, ce_r {stats['ce_decode']:.4f}) "
                  f"| t_mean {stats['t_mean']:.1f} | lr {lr_now:.2e} | {elapsed:.1f}s")

        if step % EVAL_EVERY == 0 and step > 0:
            val_stats = evaluate(model, val_loader)
            print(f"  [eval] step {step} | val_loss {val_stats['val_loss']:.4f} "
                  f"(mse {val_stats['val_mse']:.4f}, ce {val_stats['val_ce']:.4f})")

            if val_stats["val_loss"] < best_val_loss:
                best_val_loss = val_stats["val_loss"]
                torch.save({
                    "model_state_dict": model.state_dict(),
                    "cfg": model.cfg,
                    "step": step,
                    "val_loss": best_val_loss,
                    # Full source of the model class so the checkpoint is
                    # self-describing and can be reconstructed without this file.
                    "model_arch_src": inspect.getsource(ChannelDiffusionLM),
                    "model_arch_cls": "ChannelDiffusionLM",
                }, CKPT_PATH)
                print(f"  [ckpt] saved new best (val_loss={best_val_loss:.4f}) -> {CKPT_PATH}")

        if step % SAMPLE_EVERY == 0 and step > 0:
            print(f"  [sample] step {step} reverse-diffusion sanity check:")
            sample_batch = next(iter(val_loader))
            sanity_check_sample(model, sample_batch, tokenizer)

        step += 1

    print("training complete.")


train(model, train_loader, val_loader, hf_tokenizer, total_steps=TOTAL_STEPS)
